### ISSUE TITLE
TypeError: version_from_git() got an unexpected keyword argument 'version_scheme'

### ISSUE THREAD

**Issue by xposix** [dolfinus/setuptools-git-versioning#100]
I am getting an error when executing `$ python -m setuptools_git_versioning` in my current project. 

```
pdm.termui: Stable pins:
pdm.termui:                      python None
pdm.termui:   setuptools-git-versioning 2.0.0
pdm.termui:                  setuptools 69.2.0
pdm.termui:                       wheel 0.43.0
pdm.termui:                   packaging 24.0
pdm.termui: Installing packaging@24.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/49/df/1fceb2f8900f8639e278b056416d49134fb8d84c5942ffaa01ad34782422/packaging-24.0-py3-none-any.whl (from https://pypi.org/simple/packaging/)>
pdm.termui: Installing setuptools@69.2.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/92/e1/1c8bb3420105e70bdf357d57dd5567202b4ef8d27f810e98bb962d950834/setuptools-69.2.0-py3-none-any.whl (from https://pypi.org/simple/setuptools/)>
pdm.termui: Installing setuptools-git-versioning@2.0.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/2d/15/37202ca349df8056d67c29a7b4bf27daae22dcb5ce7d7e21f4db1f2b6f34/setuptools_git_versioning-2.0.0-py3-none-any.whl (from https://pypi.org/simple/setuptools-git-versioning/)>
pdm.termui: Installing wheel@0.43.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/7d/cd/d7460c9a869b16c3dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-none-any.whl (from https://pypi.org/simple/wheel/)>
pdm.termui: Synchronization complete.
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/vscode/.local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/vscode/.local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/home/vscode/.local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
pdm.termui:     return hook(config_settings)
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
pdm.termui:     return self._get_build_requires(config_settings, requirements=['wheel'])
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
pdm.termui:     self.run_setup()
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
pdm.termui:     exec(code, locals())
pdm.termui:   File "<string>", line 1, in <module>
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
pdm.termui:     return distutils.core.setup(**attrs)
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
pdm.termui:     _setup_distribution = dist = klass(attrs)
pdm.termui:                                  ^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/dist.py", line 307, in __init__
pdm.termui:     _Distribution.__init__(self, dist_attrs)
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
pdm.termui:     self.finalize_options()
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/dist.py", line 658, in finalize_options
pdm.termui:     ep(self)
pdm.termui:   File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools_git_versioning.py", line 256, in infer_version
pdm.termui:     version = version_from_git(dist.metadata.name, **config, root=root)
pdm.termui:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui: TypeError: version_from_git() got an unexpected keyword argument 'version_scheme'
Traceback (most recent call last):
  File "/home/vscode/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/cli/commands/build.py", line 112, in handle
    self.do_build(
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/cli/commands/build.py", line 63, in do_build
    loc = WheelBuilder(project.root, project.environment).build(dest, config_settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/builders/base.py", line 261, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/dist.py", line 307, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools/dist.py", line 658, in finalize_options
    ep(self)
  File "/tmp/pdm-build-env-amt0c5vy-shared/lib/python3.11/site-packages/setuptools_git_versioning.py", line 256, in infer_version
    version = version_from_git(dist.metadata.name, **config, root=root)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: version_from_git() got an unexpected keyword argument 'version_scheme'
make: *** [Makefile:67: build] Error 1
```

This is my configuration with few bits redacted and substituted by `(...)`:
```
[build-system]
requires = ["setuptools>=62", "wheel", "setuptools-git-versioning>=2.0,<3",]
build-backend = "setuptools.build_meta"

[tool.pdm.dev-dependencies]
format = [
    "black>=23.10.1",
    "flake8>=6.1.0",
    "isort>=5.12.0",
    "mypy>=1.6.1",
]
test = [
    "pyyaml>=6.0.1",
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "jsonschema>=4.20.0",
]

[project]
name = "mob_lib"
dynamic = ["version"]
requires-python = ">=3.10"
keywords = ["mob_lib"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Environment :: Other Environment",
    "Operating System :: OS Independent",
]
dependencies = [
   (...)
    "connexion",
    "typing",
    "six",
    "flask",
    "python-dotenv",
    "inflection",
    "SQLAlchemy",
]


[tool.setuptools]
packages =(...)
include-package-data = true

[tool.setuptools.package-dir]
(...)


[tool.setuptools-git-versioning]
enabled = true
version_scheme = "python"
local_scheme = "dirty-tag"

```

A little bit more context: we have been trying several ways to automatically generate a version number with other Python tools. The challenge in our case is that we cannot use git tags, as they are used by the release manager software and they are 20-30 characters long with several fields separated by '-' and '_'. 

Any idea what I am doing wrong? Thanks!

**Comment by dolfinus** [comment]
Where did you get these options from?
```
version_scheme = "python"
local_scheme = "dirty-tag"
```

**Comment by xposix** [comment]
LOL that's my AI copilot. I never thought to check those, that must be the issue then I will have a look into your official documentation tomorrow. Thanks for your prompt answer!
