### ISSUE TITLE
Source distribution requires 'requirements.txt'

### ISSUE THREAD

**Issue by WildCard65** [dolfinus/setuptools-git-versioning#3]
There's an issue with this project for when the source distribution is used over the pre-built wheels, the issue is ```FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'```

To fix this, you either need to drop usage of ```requirements.txt``` in ```setup.py``` or package it with the source distribution.

**Comment by dolfinus** [comment]
Hello.

Please check v1.1.9, I've added `requirements.txt` into sdist archive.

**Comment by WildCard65** [comment]
Actually, @ErikMinekus needs to test this as they were the one who had the problem.

**Comment by ErikMinekus** [comment]
That's solved, but you require the latest setuptools for Python >= 3.5, so any package that uses this library won't install unless setuptools is fully upgraded.

**Comment by WildCard65** [comment]
Do you have a Python traceback to help?

**Comment by ErikMinekus** [comment]
```bash
$ python3 -m pip install --user ./ambuild
Processing ./ambuild
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*.pyo' found under directory '*'
    warning: no previously-included files matching '*.orig' found under directory '*'

    Installed /tmp/pip-3xxex8yq-build/.eggs/setuptools_git_versioning-1.1.9-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-3xxex8yq-build/setup.py", line 75, in <module>
        zip_safe = False)
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1085, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 695, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (setuptools 20.7.0 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=49.6; python_version >= "3.5"'))
```

**Comment by dolfinus** [comment]
I've removed such strong restrictions for setuptools version, please check v1.1.10.
But I don't really think that somebody will use setuptools 20.7 with python3.5 in 2020.

**Comment by ErikMinekus** [comment]
That's fair, but it's the version that `apt install python3-setuptools` installs on Ubuntu Xenial LTS. I now know that I should be using `pip install setuptools`.

Anyway, for some reason `flake8` is failing to install now:
```bash
$ python3 -m pip install --user ./ambuild
Processing ./ambuild
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*.pyo' found under directory '*'
    warning: no previously-included files matching '*.orig' found under directory '*'

    Installed /tmp/pip-pxg0f_da-build/.eggs/setuptools_git_versioning-1.1.10-py3.5.egg
    Searching for flake8>=3.8; python_version >= "3.5"
    Reading https://pypi.python.org/simple/flake8/
    Best match: flake8 3.8.3
    Downloading https://files.pythonhosted.org/packages/99/eb/cc2bbe9b242a79d2c5820911f21875a138aafa3dc2c3b9b34ba714f9fef9/flake8-3.8.3.tar.gz#sha256=f04b9fcbac03b0a3e58c0ab3a0ecc462e023a9faf046d57794184028123aa208
    Processing flake8-3.8.3.tar.gz
    Writing /tmp/easy_install-j1jnazks/flake8-3.8.3/setup.cfg
    Running flake8-3.8.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-j1jnazks/flake8-3.8.3/egg-dist-tmp-4tr5_ehw
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    no previously-included directories found matching 'docs/build/'
    warning: install_lib: 'build/lib' does not exist -- no Python modules to install

    zip_safe flag not set; analyzing archive contents...
    Moving UNKNOWN-0.0.0-py3.5.egg to /tmp/pip-pxg0f_da-build/.eggs

    Installed /tmp/pip-pxg0f_da-build/.eggs/UNKNOWN-0.0.0-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-pxg0f_da-build/setup.py", line 75, in <module>
        zip_safe = False)
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'flake8>=3.8; python_version >= "3.5"' distribution was not found and is required by setuptools-git-versioning
```

Manually running `python3 -m pip install flake8` does work.

**Comment by WildCard65** [comment]
flake8 actually isn't required by setuptools-git-versioning. @dolfinus I seriously recommend splitting setup.py and requirements.txt

**Comment by dolfinus** [comment]
You're right, I've removed flake8 from requirements.txt completely, v1.1.11 is released.

**Comment by ErikMinekus** [comment]
Works fine now, I think this can be closed.
