### ISSUE TITLE
Strange Python error

### ISSUE THREAD

**Issue by WildCard65** [dolfinus/setuptools-git-versioning#4]
Just encountered an extremely weird issue with v1.1.11 on Python 3.5 for MacOS when using egg builds:
```
2020-08-19T19:24:34.4315910Z      command: /Users/runner/hostedtoolcache/Python/3.5.9/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-x1d6tu0o/setup.py'"'"'; __file__='"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-x1d6tu0o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-pip-egg-info-ld154gba
2020-08-19T19:24:34.4320760Z          cwd: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-x1d6tu0o/
2020-08-19T19:24:34.4321620Z     Complete output (35 lines):
2020-08-19T19:24:34.4323290Z     /Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
2020-08-19T19:24:34.4325950Z       warnings.warn(msg)
2020-08-19T19:24:34.4327890Z     warning: no previously-included files matching '__pycache__' found under directory '*'
2020-08-19T19:24:34.4329030Z     warning: no previously-included files matching '*.pyc' found under directory '*'
2020-08-19T19:24:34.4329810Z     warning: no previously-included files matching '*.pyo' found under directory '*'
2020-08-19T19:24:34.4330610Z     warning: no previously-included files matching '*.orig' found under directory '*'
2020-08-19T19:24:34.4330930Z     
2020-08-19T19:24:34.4334660Z     Installed /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-x1d6tu0o/.eggs/setuptools_git_versioning-1.1.11-py3.5.egg
2020-08-19T19:24:34.4336130Z     Traceback (most recent call last):
2020-08-19T19:24:34.4338470Z       File "<string>", line 1, in <module>
2020-08-19T19:24:34.4339660Z       File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-x1d6tu0o/setup.py", line 75, in <module>
2020-08-19T19:24:34.4339860Z         zip_safe = False)
2020-08-19T19:24:34.4340070Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/distutils/core.py", line 108, in setup
2020-08-19T19:24:34.4340820Z         _setup_distribution = dist = klass(attrs)
2020-08-19T19:24:34.4341820Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/setuptools/dist.py", line 318, in __init__
2020-08-19T19:24:34.4342020Z         _Distribution.__init__(self, attrs)
2020-08-19T19:24:34.4342230Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/distutils/dist.py", line 281, in __init__
2020-08-19T19:24:34.4342410Z         self.finalize_options()
2020-08-19T19:24:34.4343080Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/setuptools/dist.py", line 376, in finalize_options
2020-08-19T19:24:34.4343240Z         ep.load()(self, ep.name, value)
2020-08-19T19:24:34.4343930Z       File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-x1d6tu0o/.eggs/setuptools_git_versioning-1.1.11-py3.5.egg/setuptools_git_versioning.py", line 87, in parse_config
2020-08-19T19:24:34.4344160Z         if not isinstance(value, Mapping):
2020-08-19T19:24:34.4344360Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/abc.py", line 191, in __instancecheck__
2020-08-19T19:24:34.4344540Z         return cls.__subclasscheck__(subclass)
2020-08-19T19:24:34.4345290Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/abc.py", line 226, in __subclasscheck__
2020-08-19T19:24:34.4345530Z         if issubclass(subclass, scls):
2020-08-19T19:24:34.4345750Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/typing.py", line 1175, in __subclasscheck__
2020-08-19T19:24:34.4345920Z         return super().__subclasscheck__(cls)
2020-08-19T19:24:34.4346120Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/abc.py", line 207, in __subclasscheck__
2020-08-19T19:24:34.4346280Z         ok = cls.__subclasshook__(subclass)
2020-08-19T19:24:34.4346480Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/typing.py", line 907, in __extrahook__
2020-08-19T19:24:34.4346660Z         if issubclass(subclass, scls):
2020-08-19T19:24:34.4346860Z       File "/Users/runner/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/typing.py", line 1169, in __subclasscheck__
2020-08-19T19:24:34.4347090Z         raise TypeError("Parameterized generics cannot be used with class "
2020-08-19T19:24:34.4347250Z     TypeError: Parameterized generics cannot be used with class or instance checks
```

Error suggests that for whatever reason, "typing.Mapping" is used instead of "collections.abc.Mapping"

Also, you're import checking for "collections.abc" is mispelled as "collections.abs" which always fails.

**Comment by dolfinus** [comment]
Hello.

Try v1.1.12, please.

**Comment by WildCard65** [comment]
@dolfinus Still the same strange issue.

IDK why Python is using typing.Mapping as the error is saying is happening.

**Comment by dolfinus** [comment]
Let's try v1.1.13, if it still failing, I'll replace Mapping with just dict.

**Comment by WildCard65** [comment]
5 days late but here's a report:
Python 3.3 support still not working (No module named "typing")
Python 3.5 errored with: No module named "six"

**Comment by dolfinus** [comment]
I cannot reproduce that:
2.7:
```
 ~ docker run -it python:2.7 bash
root@57e43221f374:/# pip install setuptools_git_versioning
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting setuptools_git_versioning
  Downloading setuptools_git_versioning-1.1.13-py2-none-any.whl (5.1 kB)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python2.7/site-packages (from setuptools_git_versioning) (1.14.0)
Requirement already satisfied: setuptools<=44.1; python_version < "3" in /usr/local/lib/python2.7/site-packages (from setuptools_git_versioning) (44.1.0)
Requirement already satisfied: typing>=3.7; python_version < "3" in /usr/local/lib/python2.7/site-packages (from setuptools_git_versioning) (3.7.4.1)
Installing collected packages: setuptools-git-versioning
Successfully installed setuptools-git-versioning-1.1.13
WARNING: You are using pip version 20.0.2; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@57e43221f374:/# python
Python 2.7.18 (default, Apr 20 2020, 19:27:10) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_git_versioning
>>> setuptools_git_versioning.version_from_git()
fatal: not a git repository (or any of the parent directories): .git
'0.0.1'
```

3.3:
```
 ~ docker run -it python:3.3 bash    
root@cf427ce2ec7f:/# pip install setuptools_git_versioning
Collecting setuptools_git_versioning
  Downloading https://files.pythonhosted.org/packages/9b/bf/f84d76a19e8afb40bd29437a330570f36bda4de47145d3ee13d7d3604c67/setuptools_git_versioning-1.1.13-py3-none-any.whl
Collecting typing<3.7,>=3.6; python_version == "3.3" (from setuptools_git_versioning)
  Downloading https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting six>=1.13.0 (from setuptools_git_versioning)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools<=39.2; python_version == "3.3" in /usr/local/lib/python3.3/site-packages (from setuptools_git_versioning)
Installing collected packages: typing, six, setuptools-git-versioning
Successfully installed setuptools-git-versioning-1.1.13 six-1.15.0 typing-3.6.6
You are using pip version 9.0.1, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@cf427ce2ec7f:/# python
Python 3.3.7 (default, Sep 19 2017, 23:13:00) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_git_versioning
>>> setuptools_git_versioning.get_tags()
fatal: Not a git repository (or any of the parent directories): .git
[]
>>> setuptools_git_versioning.version_from_git()
fatal: Not a git repository (or any of the parent directories): .git
'0.0.1'
```

3.4:
```
 ~ docker run -it python:3.4 bash
root@28dae0466e68:/# pip install setuptools_git_versioning
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting setuptools_git_versioning
  Downloading https://files.pythonhosted.org/packages/9b/bf/f84d76a19e8afb40bd29437a330570f36bda4de47145d3ee13d7d3604c67/setuptools_git_versioning-1.1.13-py3-none-any.whl
Collecting typing<3.7,>=3.6; python_version == "3.4" (from setuptools_git_versioning)
  Downloading https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting six>=1.13.0 (from setuptools_git_versioning)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting setuptools<=39.2; python_version == "3.4" (from setuptools_git_versioning)
  Downloading https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl (567kB)
    100% |████████████████████████████████| 573kB 3.4MB/s 
Installing collected packages: typing, six, setuptools, setuptools-git-versioning
  Found existing installation: setuptools 40.8.0
    Uninstalling setuptools-40.8.0:
      Successfully uninstalled setuptools-40.8.0
Successfully installed setuptools-39.2.0 setuptools-git-versioning-1.1.13 six-1.15.0 typing-3.6.6
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@28dae0466e68:/# python
Python 3.4.10 (default, Mar 20 2019, 00:50:15) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_git_versioning
>>> setuptools_git_versioning.version_from_git()
fatal: Not a git repository (or any of the parent directories): .git
'0.0.1'
```

3.5
```
 ~ docker run -it python:3.5 bash
root@a361e44e324b:/# pip install setuptools_git_versioning
Collecting setuptools_git_versioning
  Downloading setuptools_git_versioning-1.1.13-py3-none-any.whl (5.1 kB)
Requirement already satisfied: setuptools; python_version >= "3.5" in /usr/local/lib/python3.5/site-packages (from setuptools_git_versioning) (49.3.1)
Collecting six>=1.13.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, setuptools-git-versioning
Successfully installed setuptools-git-versioning-1.1.13 six-1.15.0
root@a361e44e324b:/# python
Python 3.5.9 (default, Aug  5 2020, 08:59:28) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_git_versioning
>>> setuptools_git_versioning.version_from_git()
fatal: not a git repository (or any of the parent directories): .git
'0.0.1'
```

3.6:
```
 ~ docker run -it python:3.6 bash                                                                                                                                                                                 Пт 28 авг 2020 09:57:22
root@1536322888d8:/# pip install setuptools_git_versioning
Collecting setuptools_git_versioning
  Downloading setuptools_git_versioning-1.1.13-py3-none-any.whl (5.1 kB)
Requirement already satisfied: setuptools; python_version >= "3.5" in /usr/local/lib/python3.6/site-packages (from setuptools_git_versioning) (49.6.0)
Collecting six>=1.13.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, setuptools-git-versioning
Successfully installed setuptools-git-versioning-1.1.13 six-1.15.0
root@1536322888d8:/# python
Python 3.6.12 (default, Aug 18 2020, 04:20:58) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_git_versioning
>>> setuptools_git_versioning.version_from_git()
fatal: not a git repository (or any of the parent directories): .git
'0.0.1'
```

3.7:
```
 ~ docker run -it python:3.7 bash
root@ed821e734682:/# pip install setuptools_git_versioning
Collecting setuptools_git_versioning
  Downloading setuptools_git_versioning-1.1.13-py3-none-any.whl (5.1 kB)
Requirement already satisfied: setuptools; python_version >= "3.5" in /usr/local/lib/python3.7/site-packages (from setuptools_git_versioning) (49.2.0)
Collecting six>=1.13.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, setuptools-git-versioning
Successfully installed setuptools-git-versioning-1.1.13 six-1.15.0
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@ed821e734682:/# python
Python 3.7.8 (default, Jul 22 2020, 12:48:54) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_git_versioning
>>> setuptools_git_versioning.version_from_git()
fatal: not a git repository (or any of the parent directories): .git
'0.0.1'
```

3.8
```
 ~ docker run -it python:3.8 bash
root@dcc10a512dd3:/# pip install setuptools_git_versioning
Collecting setuptools_git_versioning
  Downloading setuptools_git_versioning-1.1.13-py3-none-any.whl (5.1 kB)
Collecting six>=1.13.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: setuptools; python_version >= "3.5" in /usr/local/lib/python3.8/site-packages (from setuptools_git_versioning) (49.2.0)
Installing collected packages: six, setuptools-git-versioning
Successfully installed setuptools-git-versioning-1.1.13 six-1.15.0
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@dcc10a512dd3:/# python
Python 3.8.5 (default, Jul 22 2020, 12:28:11) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools_git_versioning
>>> setuptools_git_versioning.version_from_git()
fatal: not a git repository (or any of the parent directories): .git
'0.0.1'
```

Do you have pip logs?
