### ISSUE TITLE
Cannot use setuptools-git-versioning with Python version < 3.11

### ISSUE THREAD

**Issue by pipinfitriadi** [dolfinus/setuptools-git-versioning#86]
Got `ModuleNotFoundError: No module named 'tomllib'` on Python 3.7

```sh
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools_git_versioning.py", line 192, in _read_toml
          import tomllib
      ModuleNotFoundError: No module named 'tomllib'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 512, in loads
          multibackslash)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 778, in load_line
          value, vtype = self.load_value(pair[1], strictly_valid)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 880, in load_value
          return (self.load_array(v), "array")
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 1026, in load_array
          nval, ntype = self.load_value(a[i])
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 883, in load_value
          self.load_inline_object(v, inline_object)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 680, in load_inline_object
          multibackslash)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 778, in load_line
          value, vtype = self.load_value(pair[1], strictly_valid)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 849, in load_value
          raise ValueError("Found tokens after a closed " +
      ValueError: Found tokens after a closed string. Invalid TOML.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/mylaptop/venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/mylaptop/venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/mylaptop/venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 490, in __init__
          for k, v in attrs.items()
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 925, in finalize_options
          ep(self)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools_git_versioning.py", line 272, in infer_version
          toml_config = _read_toml(root=root)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/setuptools_git_versioning.py", line 199, in _read_toml
          parsed_file = toml.load(file_path)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 134, in load
          return loads(ffile.read(), _dict, decoder)
        File "/private/var/folders/2c/6g1jt88939j_j4v2qf1tqg4m0000gn/T/pip-build-env-l1tvgbac/overlay/lib/python3.7/site-packages/toml/decoder.py", line 514, in loads
          raise TomlDecodeError(str(err), original, pos)
      toml.decoder.TomlDecodeError: Found tokens after a closed string. Invalid TOML. (line 37 column 1 char 1361)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by dolfinus** [comment]
Hi.

Check your `pyproject.toml`, actual exception message is in the last line: `ValueError: Found tokens after a closed string. Invalid TOML.`

**Comment by pipinfitriadi** [comment]
Ok got it.. thanks @dolfinus
